#!/usr/bin/env python3
"""
Embed tufted_panel.stl into preview.html as a base64 blob so the page works
from file:// (no local web server needed).

Run after every regeneration:
    python3 build_preview.py
"""

from __future__ import annotations
import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
STL = HERE / "tufted_panel.stl"
OUT = HERE / "preview.html"

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Tufted Panel - STL Preview</title>
<style>
  html, body { margin: 0; height: 100%; background: #0a0a0a; color: #e5e7eb;
               font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
  #viewer { position: fixed; inset: 0; }
  .panel {
    position: fixed; top: 16px; left: 16px; padding: 14px 16px;
    background: rgba(15, 23, 32, 0.78); backdrop-filter: blur(8px);
    border: 1px solid rgba(94, 234, 212, 0.25); border-radius: 12px;
    max-width: 340px; line-height: 1.45; font-size: 13px;
  }
  .panel h1 { margin: 0 0 6px 0; font-size: 15px; color: #5eead4; letter-spacing: 0.02em; }
  .panel small { color: #9ca3af; }
  .panel kbd { background:#1f2937; border:1px solid #374151; padding:1px 5px;
               border-radius:4px; font-size:11px; }
  .panel button { margin-top:10px; background:#0f766e; color:#f0fdfa;
                  border:0; padding:6px 10px; border-radius:6px; cursor:pointer;
                  font-size:12px; }
  .panel button:hover { background:#0d9488; }
  .stats { position: fixed; bottom: 14px; left: 16px; font-size: 12px; color: #9ca3af; }
  .drop { position: fixed; inset: 0; pointer-events: none;
          border: 4px dashed transparent; box-sizing: border-box; transition: border-color .15s; }
  .drop.over { border-color: #5eead4; }
</style>
</head>
<body>
<div id="viewer"></div>
<div class="drop" id="drop"></div>

<div class="panel">
  <h1>Tufted panel - STL preview</h1>
  <div>Chesterfield-style diamond-tufted relief, 120 &times; 150 &times; 12 mm.
       Watertight mesh, ready for CAM.</div>
  <div style="margin-top: 8px;">
    <small>
      <kbd>drag</kbd> orbit &nbsp;
      <kbd>scroll</kbd> zoom &nbsp;
      <kbd>right-drag</kbd> pan
    </small>
  </div>
  <div>
    <input type="file" id="file" accept=".stl" style="display:none">
    <button id="loadBtn">Load a different .stl</button>
  </div>
</div>

<div class="stats" id="stats">Loading tufted panel &hellip;</div>

<!-- Embedded STL (base64). Generated by build_preview.py. -->
<script id="stl-data" type="application/octet-stream;base64">__STL_BASE64__</script>

<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.160.0/build/three.module.js",
    "three/addons/": "https://unpkg.com/three@0.160.0/examples/jsm/"
  }
}
</script>

<script type="module">
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';

const stats = document.getElementById('stats');

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0a0a0a);

const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, 0.1, 2000);
camera.position.set(160, -200, 160);
camera.up.set(0, 0, 1);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(devicePixelRatio);
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.getElementById('viewer').appendChild(renderer.domElement);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.target.set(60, 75, 6);

scene.add(new THREE.AmbientLight(0xffffff, 0.30));
const key = new THREE.DirectionalLight(0xfff1d6, 1.2);
key.position.set(120, -80, 160);
key.castShadow = true;
key.shadow.mapSize.set(2048, 2048);
const d = 120;
Object.assign(key.shadow.camera, { left:-d, right:d, top:d, bottom:-d, near:1, far:500 });
scene.add(key);
const fill = new THREE.DirectionalLight(0x9ecaff, 0.35); fill.position.set(-120, 80, 80); scene.add(fill);
const rim  = new THREE.DirectionalLight(0xffffff, 0.30); rim.position.set(0, 160, 60);   scene.add(rim);

// Spoilboard plane.
const ground = new THREE.Mesh(
  new THREE.PlaneGeometry(600, 600),
  new THREE.MeshStandardMaterial({ color: 0x15191f, roughness: 0.95 })
);
ground.receiveShadow = true;
scene.add(ground);

let currentMesh = null;
const loader = new STLLoader();

function showGeometry(geometry, label) {
  if (currentMesh) {
    scene.remove(currentMesh);
    currentMesh.geometry.dispose();
  }
  geometry.computeVertexNormals();
  const material = new THREE.MeshStandardMaterial({
    color: 0x2a2a2e, roughness: 0.65, metalness: 0.05
  });
  currentMesh = new THREE.Mesh(geometry, material);
  currentMesh.castShadow = true;
  currentMesh.receiveShadow = true;
  scene.add(currentMesh);

  geometry.computeBoundingBox();
  const bb = geometry.boundingBox;
  const dx = (bb.max.x - bb.min.x).toFixed(2);
  const dy = (bb.max.y - bb.min.y).toFixed(2);
  const dz = (bb.max.z - bb.min.z).toFixed(2);
  const ntri = geometry.attributes.position.count / 3;
  stats.textContent = `${label}  -  ${ntri.toLocaleString()} tri  -  ${dx} x ${dy} x ${dz} mm`;

  // Recentre the camera target on the loaded geometry.
  controls.target.set(
    (bb.min.x + bb.max.x) / 2,
    (bb.min.y + bb.max.y) / 2,
    (bb.min.z + bb.max.z) / 2
  );
}

function loadFromBase64() {
  const node = document.getElementById('stl-data');
  const b64 = (node && node.textContent || '').trim();
  if (!b64 || b64 === '__' + 'STL_BASE64__') {
    stats.textContent = 'No embedded STL. Drop a .stl file here.';
    return;
  }
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  const geo = loader.parse(buf.buffer);
  showGeometry(geo, 'tufted_panel.stl (embedded)');
}

function loadFromFile(file) {
  const r = new FileReader();
  r.onload = e => {
    const geo = loader.parse(e.target.result);
    showGeometry(geo, file.name);
  };
  r.readAsArrayBuffer(file);
}

if (location.protocol.startsWith('http')) {
  loader.load(
    'tufted_panel.stl',
    g => showGeometry(g, 'tufted_panel.stl'),
    undefined,
    () => loadFromBase64()
  );
} else {
  loadFromBase64();
}

const fileInput = document.getElementById('file');
document.getElementById('loadBtn').addEventListener('click', () => fileInput.click());
fileInput.addEventListener('change', e => {
  if (e.target.files.length) loadFromFile(e.target.files[0]);
});

const drop = document.getElementById('drop');
addEventListener('dragenter', e => { e.preventDefault(); drop.classList.add('over'); });
addEventListener('dragover',  e => { e.preventDefault(); });
addEventListener('dragleave', e => { if (e.target === document.documentElement) drop.classList.remove('over'); });
addEventListener('drop', e => {
  e.preventDefault(); drop.classList.remove('over');
  if (e.dataTransfer.files.length) loadFromFile(e.dataTransfer.files[0]);
});

addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

(function loop() {
  requestAnimationFrame(loop);
  controls.update();
  renderer.render(scene, camera);
})();
</script>
</body>
</html>
"""


def main() -> None:
    if not STL.exists():
        raise SystemExit(f"Missing {STL}. Run generate_tufted.py first.")
    b64 = base64.b64encode(STL.read_bytes()).decode("ascii")
    OUT.write_text(HTML.replace("__STL_BASE64__", b64))
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"Wrote {OUT}  ({size_mb:.2f} MB, with STL embedded)")
    print("Open by double-clicking the file - no web server required.")


if __name__ == "__main__":
    main()
