#!/usr/bin/env python3
"""
Bake rose.stl into preview.html as a base64 blob so the page works when
opened directly with file:// (no local web server required).

Run after every regeneration of rose.stl:
    python3 build_preview.py
"""

from __future__ import annotations
import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
STL = HERE / "rose.stl"
OUT = HERE / "preview.html"

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>3D Rose - STL Preview</title>
<style>
  html, body { margin: 0; height: 100%; background: #0a0a0a; color: #e5e7eb;
               font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
  #viewer { position: fixed; inset: 0; }
  .panel {
    position: fixed; top: 16px; left: 16px; padding: 14px 16px;
    background: rgba(15, 23, 32, 0.78); backdrop-filter: blur(8px);
    border: 1px solid rgba(94, 234, 212, 0.25); border-radius: 12px;
    max-width: 340px; line-height: 1.45; font-size: 13px;
  }
  .panel h1 { margin: 0 0 6px 0; font-size: 15px; color: #5eead4; letter-spacing: 0.02em; }
  .panel small { color: #9ca3af; }
  .panel kbd { background:#1f2937; border:1px solid #374151; padding:1px 5px;
               border-radius:4px; font-size:11px; }
  .panel button { margin-top:10px; background:#0f766e; color:#f0fdfa;
                  border:0; padding:6px 10px; border-radius:6px; cursor:pointer;
                  font-size:12px; }
  .panel button:hover { background:#0d9488; }
  .stats { position: fixed; bottom: 14px; left: 16px; font-size: 12px; color: #9ca3af; }
  .err { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
         color: #fca5a5; background: #1f2937; padding: 14px 18px; border-radius: 8px;
         border: 1px solid #7f1d1d; max-width: 480px; }
  .drop { position: fixed; inset: 0; pointer-events: none;
          border: 4px dashed transparent; box-sizing: border-box; transition: border-color .15s; }
  .drop.over { border-color: #5eead4; }
</style>
</head>
<body>
<div id="viewer"></div>
<div class="drop" id="drop"></div>

<div class="panel">
  <h1>3D Rose - STL preview</h1>
  <div>Parametric rose for CNC routing on a wooden blank.</div>
  <div style="margin-top: 8px;">
    <small>
      <kbd>drag</kbd> orbit &nbsp;
      <kbd>scroll</kbd> zoom &nbsp;
      <kbd>right-drag</kbd> pan
    </small>
  </div>
  <div style="margin-top:10px;">
    <small>Dashed teal box = 100 &times; 100 &times; 40 mm stock blank.<br>
           Axes mark the CNC work origin (top-centre of stock).</small>
  </div>
  <div>
    <input type="file" id="file" accept=".stl" style="display:none">
    <button id="loadBtn">Load a different .stl</button>
  </div>
</div>

<div class="stats" id="stats">Loading rose &hellip;</div>

<!-- Embedded STL (base64). Generated by build_preview.py. -->
<script id="stl-data" type="application/octet-stream;base64">__STL_BASE64__</script>

<script type="importmap">
{
  "imports": {
    "three": "https://unpkg.com/three@0.160.0/build/three.module.js",
    "three/addons/": "https://unpkg.com/three@0.160.0/examples/jsm/"
  }
}
</script>

<script type="module">
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';

const stats = document.getElementById('stats');

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x0a0a0a);

const camera = new THREE.PerspectiveCamera(45, innerWidth / innerHeight, 0.1, 2000);
camera.position.set(120, -140, 110);
camera.up.set(0, 0, 1);

const renderer = new THREE.WebGLRenderer({ antialias: true });
renderer.setPixelRatio(devicePixelRatio);
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.getElementById('viewer').appendChild(renderer.domElement);

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.target.set(0, 0, 15);

scene.add(new THREE.AmbientLight(0xffffff, 0.35));
const key = new THREE.DirectionalLight(0xfff1d6, 1.1);
key.position.set(80, -60, 120);
key.castShadow = true;
key.shadow.mapSize.set(2048, 2048);
const d = 80;
Object.assign(key.shadow.camera, { left:-d, right:d, top:d, bottom:-d, near:1, far:400 });
scene.add(key);
const fill = new THREE.DirectionalLight(0x8ad8ff, 0.45); fill.position.set(-90, 60, 60); scene.add(fill);
const rim  = new THREE.DirectionalLight(0xffffff, 0.35); rim.position.set(0, 100, 30); scene.add(rim);

const ground = new THREE.Mesh(
  new THREE.PlaneGeometry(400, 400),
  new THREE.MeshStandardMaterial({ color: 0x1a1f24, roughness: 0.95 })
);
ground.receiveShadow = true;
scene.add(ground);

// Stock outline 100x100x40 mm.
const sx=100, sy=100, sz=40;
const stockEdges = new THREE.EdgesGeometry(new THREE.BoxGeometry(sx, sy, sz));
const stockLines = new THREE.LineSegments(
  stockEdges,
  new THREE.LineDashedMaterial({ color: 0x14b8a6, dashSize: 3, gapSize: 2 })
);
stockLines.position.set(0, 0, sz/2);
stockLines.computeLineDistances();
scene.add(stockLines);

// Work-origin axes at top-centre of stock.
const axes = new THREE.AxesHelper(20);
axes.position.set(0, 0, sz);
scene.add(axes);

let currentMesh = null;
const loader = new STLLoader();

function showGeometry(geometry, label) {
  if (currentMesh) {
    scene.remove(currentMesh);
    currentMesh.geometry.dispose();
  }
  geometry.computeVertexNormals();
  const material = new THREE.MeshStandardMaterial({
    color: 0xb71c3a, roughness: 0.55, metalness: 0.05
  });
  currentMesh = new THREE.Mesh(geometry, material);
  currentMesh.castShadow = true;
  currentMesh.receiveShadow = true;
  scene.add(currentMesh);

  geometry.computeBoundingBox();
  const bb = geometry.boundingBox;
  const dx = (bb.max.x - bb.min.x).toFixed(2);
  const dy = (bb.max.y - bb.min.y).toFixed(2);
  const dz = (bb.max.z - bb.min.z).toFixed(2);
  const ntri = geometry.attributes.position.count / 3;
  stats.textContent = `${label}  -  ${ntri.toLocaleString()} tri  -  ${dx} x ${dy} x ${dz} mm`;
}

function loadFromBase64() {
  const node = document.getElementById('stl-data');
  const b64 = (node && node.textContent || '').trim();
  if (!b64 || b64 === '__' + 'STL_BASE64__') {
    stats.textContent = 'No embedded STL. Drop a .stl file or click "Load a different .stl".';
    return;
  }
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  const geo = loader.parse(buf.buffer);
  showGeometry(geo, 'rose.stl (embedded)');
}

function loadFromFile(file) {
  const r = new FileReader();
  r.onload = e => {
    const geo = loader.parse(e.target.result);
    showGeometry(geo, file.name);
  };
  r.readAsArrayBuffer(file);
}

// Try fetching rose.stl when served over http(s); otherwise use the
// embedded base64 blob so the page works from file://.
if (location.protocol.startsWith('http')) {
  loader.load(
    'rose.stl',
    g => showGeometry(g, 'rose.stl'),
    undefined,
    () => loadFromBase64()  // 404 -> fallback
  );
} else {
  loadFromBase64();
}

// File picker.
const fileInput = document.getElementById('file');
document.getElementById('loadBtn').addEventListener('click', () => fileInput.click());
fileInput.addEventListener('change', e => {
  if (e.target.files.length) loadFromFile(e.target.files[0]);
});

// Drag and drop.
const drop = document.getElementById('drop');
addEventListener('dragenter', e => { e.preventDefault(); drop.classList.add('over'); });
addEventListener('dragover',  e => { e.preventDefault(); });
addEventListener('dragleave', e => { if (e.target === document.documentElement) drop.classList.remove('over'); });
addEventListener('drop', e => {
  e.preventDefault(); drop.classList.remove('over');
  if (e.dataTransfer.files.length) loadFromFile(e.dataTransfer.files[0]);
});

addEventListener('resize', () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
});

(function loop() {
  requestAnimationFrame(loop);
  controls.update();
  renderer.render(scene, camera);
})();
</script>
</body>
</html>
"""


def main() -> None:
    if not STL.exists():
        raise SystemExit(f"Missing {STL}. Run generate_rose.py first.")
    b64 = base64.b64encode(STL.read_bytes()).decode("ascii")
    OUT.write_text(HTML.replace("__STL_BASE64__", b64))
    size_mb = OUT.stat().st_size / (1024 * 1024)
    print(f"Wrote {OUT}  ({size_mb:.2f} MB, with STL embedded)")
    print("Open by double-clicking the file -- no web server required.")


if __name__ == "__main__":
    main()
